link:
  - src: zsh/.zshenv
    dest: ~/.zshenv
  - src: zsh/.zshrc
    dest: ~/.zshrc
  - src: neovide
    dest: ~/.config/neovide
  - src: nvim
    dest: ~/.config/nvim
  - src: lazygit/config.yml
    dest: ~/.config/lazygit/config.yml
pip_packages:
  - norminette
  - c-formatter-42
fonts:
  src_dir: fonts
  dest_dir: ~/.local/share/fonts
