linux:
  links:
    - src: zsh/.zshenv
      dest: ~/.zshenv
    - src: zsh/.zshrc
      dest: ~/.zshrc
    - src: neovide
      dest: ~/.config/neovide
    - src: nvim
      dest: ~/.config/nvim
    - src: lazygit/
      dest: ~/.config/lazygit/
  pip_packages:
    - norminette
    - c-formatter-42
  fonts:
    src_dir: fonts
    dest_dir: ~/.local/share/fonts
  gnome:
    extensions:
      - uuid: tiling-assistant@leleat-on-github
        dconf_filename: gnome/tiling-assistant.dconf
      - uuid: dash-to-dock@micxgx.gmail.com
        dconf_filename: gnome/dash-to-dock.dconf
      - uuid: clipboard-indicator@tudmotu.com
        dconf_filename: gnome/clipboard-indicator.dconf
windows:
  links:
    - src: nvim
      dest: "%LOCALAPPDATA%/nvim"

    - src: neovide
      dest: "%APPDATA%/neovide"

    - src: lazygit
      dest: "%APPDATA%/lazygit"
  pip_packages:
    - pynvim
    - norminette
    - c-formatter-42
  fonts:
    src_dir: fonts
    dest_dir: "%LOCALAPPDATA%/Microsoft/Windows/Fonts"
